version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    networks:
      - dokploy-network

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`laravel.dokploy.me`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.routers.laravel.tls.certresolver=myresolver"

networks:
  dokploy-network:
    external: true
